name: Build and Deploy the Hugo website

on:
  push:
    branches:
      - hugo

jobs:
  build-and-deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.6.0
        with:
          hugo-version: '0.115.0'
          extended: true
      - name: Build
        run: hugo
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
